---
#docker compose version
version: '3.10'

#The containers created
services:
  #The BE container contain all related main python scripts(SCP, import to DB, attendance, app (flask))
  app:
    #The dockerfile location
    build: ./app
    ports:
      #map the container to the host machine- left- local server : right- flask expose port 5000 to cinnect it from browser
      - "5000:5000"
    #The dir where the application will run from inside the container
    working_dir: /app
    # defining the environmental environments for mysql
    env_file: ./.env
    # network link to db container
    links:
      - db
    deploy:
      #The app container will always restarts because the DB container takes time to be up
      restart_policy:
        condition: always

  db:
    # The image pulled from docker hub
    image: mysql:latest
    env_file: ./.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # create a read only vol in the docker containet
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

